---

- name: loops
  hosts: localhost

  vars:
    software:
      - name: python
        required: true
      - name: maven
        required: true
      - name: java
        required: true
      - name: tomcat
        required: true
      - name: ngnix
        required: false

  tasks:
    - name: install software
      command: echo "installing {{ item.name }}"
      when: item.required=="true"
      loop: "{{ software }}"