---

- name: Install and Configure tomcat server for deployment
  hosts: nodes
  become: yes

  vars:
    tomcat_user: tomcat
    tomcat_path: /opt/tomcat/

  tasks:
    - name: Update System Package
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Create Tomcat User
      user:
        name: "{{ tomcat_user }}"
    - name: Create Tomcat Group
      group:
        name: "{{ tomcat_user }}"
    - name: Create tomcat directory
      file:
        path: "{{ tomcat_path }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        mode: 755
        recurse: yes
    - name: Download Tomcat and Unarchive
      unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.110/bin/apache-tomcat-9.0.110.tar.gz
        dest: "{{ tomcat_path }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
    - name: Start  Tomcat Server
      command: sh {{ tomcat_path }}bin/startup.sh

    - name: Allow Tcp Connections
      command: sudo ufw allow 8080/tcp